version: "2"
run:
  modules-download-mode: readonly
  tests: true
linters:
  enable:
    - misspell
    - revive
  disable:
    - errcheck
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
    revive:
      rules:
        - name: exported
          disabled: true
        - name: var-naming
          disabled: false
        - name: package-comments
          disabled: true
    staticcheck:
      checks:
        - "all"
        - "-ST*"
        - "-QF*"
  exclusions:
    generated: lax
    rules:
      - linters:
          - unused
        path: embed.go
      - linters:
          - govet
          - ineffassign
          - misspell
          - revive
          - staticcheck
          - unused
        path: internal/xrayapi/gen/
      - linters:
          - staticcheck
        path: _test\.go
    paths:
      - frontend
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - frontend
      - third_party$
      - builtin$
      - examples$
      - internal/xrayapi/gen/
