package services

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestWatchdogService_New(t *testing.T) {
	tmpDir := t.TempDir()
	xkeenSvc := NewXKeenService(filepath.Join(tmpDir, "xkeen"), tmpDir)
	w := NewWatchdogService(xkeenSvc, tmpDir, tmpDir)
	if w == nil {
		t.Fatal("expected non-nil WatchdogService")
	}
	if w.ConsecutiveFailures() != 0 {
		t.Fatalf("expected 0 consecutive failures on a fresh watchdog, got %d", w.ConsecutiveFailures())
	}
}

func TestWatchdogService_CheckHealth_Healthy(t *testing.T) {
	tmpDir := t.TempDir()
	dummy := filepath.Join(tmpDir, "xkeen")
	if err := os.WriteFile(dummy, []byte("#!/bin/sh\necho \"XKeen is running\"\n"), 0755); err != nil {
		t.Fatal(err)
	}
	xkeenSvc := NewXKeenService(dummy, tmpDir)
	w := NewWatchdogService(xkeenSvc, tmpDir, tmpDir)

	w.CheckHealth()
	if got := w.ConsecutiveFailures(); got != 0 {
		t.Fatalf("expected 0 consecutive failures after a healthy check, got %d", got)
	}
}

func TestWatchdogService_CheckHealth_FailureCounterAndTrip(t *testing.T) {
	tmpDir := t.TempDir()
	dummy := filepath.Join(tmpDir, "xkeen")
	// Exit non-zero and print an unhealthy status so isKernelStatusHealthy() is false.
	if err := os.WriteFile(dummy, []byte("#!/bin/sh\necho \"XKeen is not running\"\nexit 1\n"), 0755); err != nil {
		t.Fatal(err)
	}
	xkeenSvc := NewXKeenService(dummy, tmpDir)
	w := NewWatchdogService(xkeenSvc, tmpDir, tmpDir)

	for i := 1; i <= watchdogMaxFailures; i++ {
		w.CheckHealth()
		if got := w.ConsecutiveFailures(); got != i {
			t.Fatalf("after check %d: expected %d consecutive failures, got %d", i, i, got)
		}
	}

	// EmergencyDisarmTProxy runs asynchronously and only latches `disarmed`
	// once it has confirmed the outcome (CR-01 fix), so poll for it instead
	// of asserting immediately. iptables-save/ip6tables-save are almost
	// certainly unavailable in CI/dev sandboxes, which disarmTProxyFamily
	// treats as "nothing to do here" (ok=true), so this should resolve to
	// disarmed=true quickly.
	deadline := time.Now().Add(2 * time.Second)
	for {
		w.mu.Lock()
		disarmed := w.disarmed
		inFlight := w.disarmInFlight
		w.mu.Unlock()
		if disarmed {
			break
		}
		if time.Now().After(deadline) {
			t.Fatalf("expected watchdog to be disarmed after %d consecutive failures (disarmInFlight=%v)", watchdogMaxFailures, inFlight)
		}
		time.Sleep(5 * time.Millisecond)
	}
}

// installFakeIptables writes a fake iptables-save (prints saveOutput) and a
// fake iptables that appends its invocation args as one line to a log file,
// into a temp bin dir, and returns (saveBinPath, delBinPath, deletionsLogPath).
func installFakeIptables(t *testing.T, saveOutput string) (saveBin, delBin, logPath string) {
	t.Helper()
	binDir := t.TempDir()
	logPath = filepath.Join(binDir, "deletions.log")

	saveBin = filepath.Join(binDir, "iptables-save")
	saveScript := fmt.Sprintf("#!/bin/sh\ncat <<'EOF'\n%s\nEOF\n", saveOutput)
	if err := os.WriteFile(saveBin, []byte(saveScript), 0755); err != nil {
		t.Fatal(err)
	}

	delBin = filepath.Join(binDir, "iptables")
	delScript := fmt.Sprintf("#!/bin/sh\necho \"$@\" >> %s\nexit 0\n", logPath)
	if err := os.WriteFile(delBin, []byte(delScript), 0755); err != nil {
		t.Fatal(err)
	}

	return saveBin, delBin, logPath
}

// TestDisarmTProxyFamily_RealTargetInCustomChain verifies CR-03: XKeen's
// actual interception (per this project's own stability analysis) is a
// `-j TPROXY --on-port ...` rule, typically inside a custom chain jumped to
// from PREROUTING — not necessarily a chain literally named
// "XKEEN_TPROXY". disarmTProxyFamily must find and remove both the TPROXY
// rule itself and the PREROUTING jump into its custom chain.
func TestDisarmTProxyFamily_RealTargetInCustomChain(t *testing.T) {
	saveOutput := `# Generated by iptables-save
*mangle
:PREROUTING ACCEPT [0:0]
:xkeen - [0:0]
-A PREROUTING -j xkeen
-A xkeen -p tcp -j TPROXY --on-port 7892 --on-ip 127.0.0.1 --tproxy-mark 0x1/0x1
-A PREROUTING -j ACCEPT
COMMIT
`
	saveBin, delBin, logPath := installFakeIptables(t, saveOutput)

	removed, ok := disarmTProxyFamily(context.Background(), saveBin, delBin)
	if !ok {
		t.Fatal("expected ok=true")
	}
	if removed != 2 {
		t.Fatalf("expected 2 rules removed (the TPROXY rule + the jump into its chain), got %d", removed)
	}

	logData, err := os.ReadFile(logPath)
	if err != nil {
		t.Fatalf("expected deletions to have been invoked: %v", err)
	}
	log := string(logData)
	if !strings.Contains(log, "-D xkeen") {
		t.Errorf("expected the TPROXY rule in the custom chain to be deleted, log:\n%s", log)
	}
	if !strings.Contains(log, "-D PREROUTING -j xkeen") {
		t.Errorf("expected the PREROUTING jump into the custom chain to be deleted, log:\n%s", log)
	}
	if strings.Contains(log, "-D PREROUTING -j ACCEPT") {
		t.Errorf("unrelated PREROUTING -j ACCEPT rule must not be touched, log:\n%s", log)
	}
}

// TestDisarmTProxyFamily_LiteralChainMarker verifies the fallback match on
// tproxyChainMarker still works for builds that do name a chain
// "XKEEN_TPROXY" literally.
func TestDisarmTProxyFamily_LiteralChainMarker(t *testing.T) {
	saveOutput := `*mangle
:PREROUTING ACCEPT [0:0]
-A PREROUTING -j XKEEN_TPROXY
COMMIT
`
	saveBin, delBin, logPath := installFakeIptables(t, saveOutput)

	removed, ok := disarmTProxyFamily(context.Background(), saveBin, delBin)
	if !ok {
		t.Fatal("expected ok=true")
	}
	if removed != 1 {
		t.Fatalf("expected 1 rule removed, got %d", removed)
	}
	logData, _ := os.ReadFile(logPath)
	if !strings.Contains(string(logData), "-D PREROUTING -j XKEEN_TPROXY") {
		t.Errorf("expected the literal XKEEN_TPROXY jump to be deleted, log:\n%s", string(logData))
	}
}

// TestDisarmTProxyFamily_NoMatch verifies unrelated mangle rules are left
// untouched and no deletions are attempted.
func TestDisarmTProxyFamily_NoMatch(t *testing.T) {
	saveOutput := `*mangle
:PREROUTING ACCEPT [0:0]
-A PREROUTING -j ACCEPT
COMMIT
`
	saveBin, delBin, logPath := installFakeIptables(t, saveOutput)

	removed, ok := disarmTProxyFamily(context.Background(), saveBin, delBin)
	if !ok {
		t.Fatal("expected ok=true")
	}
	if removed != 0 {
		t.Fatalf("expected 0 rules removed, got %d", removed)
	}
	if _, err := os.Stat(logPath); err == nil {
		t.Error("expected no deletions to have been attempted for unrelated rules")
	}
}

// TestWatchdogService_EmergencyDisarmTProxy_FailureDoesNotLatch verifies the
// CR-01 fix: a failed disarm attempt must not permanently latch `disarmed`,
// so the circuit breaker can retry on a later qualifying health check
// instead of silently giving up after one transient failure.
func TestWatchdogService_EmergencyDisarmTProxy_FailureDoesNotLatch(t *testing.T) {
	removed, ok := disarmTProxyFamily(context.Background(), "iptables-save", "iptables")
	if removed != 0 {
		t.Fatalf("expected 0 rules removed when iptables-save is unavailable, got %d", removed)
	}
	if !ok {
		t.Fatalf("expected ok=true when the binary is simply missing (not a failure), got false")
	}

	// A binary that exists but always fails (permission error / lock
	// contention analogue) must report ok=false so the caller retries rather
	// than treating the attempt as a confirmed success.
	tmpDir := t.TempDir()
	failingSave := filepath.Join(tmpDir, "iptables-save")
	if err := os.WriteFile(failingSave, []byte("#!/bin/sh\nexit 1\n"), 0755); err != nil {
		t.Fatal(err)
	}
	_, ok = disarmTProxyFamily(context.Background(), failingSave, "iptables")
	if ok {
		t.Fatalf("expected ok=false when %s exits non-zero", failingSave)
	}
}

// TestWatchdogService_Stop_WaitsForInFlightDisarm verifies the WR-01 fix:
// Stop() must wait for an in-flight EmergencyDisarmTProxy goroutine rather
// than abandoning it mid-sequence during graceful shutdown/restart. This is
// verified by pointing PATH at a deliberately slow fake iptables-save so the
// disarm goroutine is still running when Stop() is called, then asserting
// Stop() actually blocked for roughly that duration instead of returning
// immediately.
func TestWatchdogService_Stop_WaitsForInFlightDisarm(t *testing.T) {
	const disarmDelay = 200 * time.Millisecond

	binDir := t.TempDir()
	slowSave := filepath.Join(binDir, "iptables-save")
	script := fmt.Sprintf("#!/bin/sh\nsleep %.2f\nexit 1\n", disarmDelay.Seconds())
	if err := os.WriteFile(slowSave, []byte(script), 0755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", binDir+string(os.PathListSeparator)+os.Getenv("PATH"))

	tmpDir := t.TempDir()
	dummy := filepath.Join(tmpDir, "xkeen")
	if err := os.WriteFile(dummy, []byte("#!/bin/sh\necho \"XKeen is not running\"\nexit 1\n"), 0755); err != nil {
		t.Fatal(err)
	}
	xkeenSvc := NewXKeenService(dummy, tmpDir)
	w := NewWatchdogService(xkeenSvc, tmpDir, tmpDir)

	// Trip the disarm directly (no need for Start()'s 30s ticker interval).
	for i := 0; i < watchdogMaxFailures; i++ {
		w.CheckHealth()
	}

	w.mu.Lock()
	inFlight := w.disarmInFlight
	w.mu.Unlock()
	if !inFlight {
		t.Fatal("expected disarmInFlight=true immediately after tripping the circuit breaker")
	}

	start := time.Now()
	w.Stop()
	elapsed := time.Since(start)

	if elapsed < disarmDelay/2 {
		t.Fatalf("Stop() returned after %v — expected it to block for roughly %v while the disarm goroutine was in flight (WR-01 regression: Stop() not waiting on the disarm goroutine)", elapsed, disarmDelay)
	}
}

// TestWatchdogService_Start_RunsFirstCheckImmediately verifies the WR-03
// fix: the first health check must not wait a full watchdogCheckInterval
// (30s) tick — it should run as soon as Start() launches the loop, so a
// kernel that's already wedged at boot is detected promptly.
func TestWatchdogService_Start_RunsFirstCheckImmediately(t *testing.T) {
	tmpDir := t.TempDir()
	dummy := filepath.Join(tmpDir, "xkeen")
	if err := os.WriteFile(dummy, []byte("#!/bin/sh\necho \"XKeen is not running\"\nexit 1\n"), 0755); err != nil {
		t.Fatal(err)
	}
	xkeenSvc := NewXKeenService(dummy, tmpDir)
	w := NewWatchdogService(xkeenSvc, tmpDir, tmpDir)

	w.Start()
	defer w.Stop()

	deadline := time.Now().Add(1 * time.Second)
	for w.ConsecutiveFailures() < 1 {
		if time.Now().After(deadline) {
			t.Fatal("expected the first health check to run promptly on Start(), well under watchdogCheckInterval")
		}
		time.Sleep(5 * time.Millisecond)
	}
}

func TestWatchdogService_CheckHealth_RecoveryResetsCounter(t *testing.T) {
	tmpDir := t.TempDir()
	dummy := filepath.Join(tmpDir, "xkeen")
	if err := os.WriteFile(dummy, []byte("#!/bin/sh\necho \"XKeen is not running\"\nexit 1\n"), 0755); err != nil {
		t.Fatal(err)
	}
	xkeenSvc := NewXKeenService(dummy, tmpDir)
	w := NewWatchdogService(xkeenSvc, tmpDir, tmpDir)

	w.CheckHealth()
	w.CheckHealth()
	if got := w.ConsecutiveFailures(); got != 2 {
		t.Fatalf("expected 2 consecutive failures, got %d", got)
	}

	if err := os.WriteFile(dummy, []byte("#!/bin/sh\necho \"XKeen is running\"\n"), 0755); err != nil {
		t.Fatal(err)
	}
	w.CheckHealth()
	if got := w.ConsecutiveFailures(); got != 0 {
		t.Fatalf("expected counter reset to 0 after recovery, got %d", got)
	}
}

func TestIsKernelStatusHealthy(t *testing.T) {
	cases := map[string]bool{
		"XKeen is running":       true,
		"Ядро активен":           true,
		"Служба XKeen активна":   true,
		"Службы активны":         true,
		"Ядро активно":           true,
		"XKeen запущен":          true,
		"Служба запущена":        true,
		"XKeen is not running":   false,
		"XKeen не запущен":       false,
		"XKeen незапущен":        false,
		"Служба не запущена":     false,
		"Служба незапущена":      false,
		"Служба не активна":      false,
		"Служба неактивна":       false,
		"Ядро не активно":        false,
		"Ядро неактивно":         false,
		"XKeen не активен":       false,
		"XKeen неактивен":        false,
		"XKeen остановлен":       false,
		"Службы остановлены":     false,
		"":                       false,
		"stopped":                false,
	}
	for status, want := range cases {
		if got := isKernelStatusHealthy(status); got != want {
			t.Errorf("isKernelStatusHealthy(%q) = %v, want %v", status, got, want)
		}
	}
}

func TestSplitIptablesRule(t *testing.T) {
	cases := []struct {
		input string
		want  []string
	}{
		{
			input: `-A PREROUTING -j xkeen`,
			want:  []string{"-A", "PREROUTING", "-j", "xkeen"},
		},
		{
			input: `-A xkeen -p tcp -m comment --comment "XKeen TProxy Rule" -j TPROXY --on-port 7892`,
			want:  []string{"-A", "xkeen", "-p", "tcp", "-m", "comment", "--comment", "XKeen TProxy Rule", "-j", "TPROXY", "--on-port", "7892"},
		},
		{
			input: `-A xkeen -m comment --comment 'Single Quoted Comment' -j ACCEPT`,
			want:  []string{"-A", "xkeen", "-m", "comment", "--comment", "Single Quoted Comment", "-j", "ACCEPT"},
		},
		{
			input: `-A xkeen -m comment --comment "Escaped \"Quotes\"" -j ACCEPT`,
			want:  []string{"-A", "xkeen", "-m", "comment", "--comment", `Escaped "Quotes"`, "-j", "ACCEPT"},
		},
		{
			input: `  -A   PREROUTING   -j   xkeen  `,
			want:  []string{"-A", "PREROUTING", "-j", "xkeen"},
		},
		{
			input: ``,
			want:  nil,
		},
	}

	for _, c := range cases {
		got := splitIptablesRule(c.input)
		if len(got) != len(c.want) {
			t.Fatalf("splitIptablesRule(%q) length = %d, want %d: %v", c.input, len(got), len(c.want), got)
		}
		for i := range got {
			if got[i] != c.want[i] {
				t.Errorf("splitIptablesRule(%q)[%d] = %q, want %q", c.input, i, got[i], c.want[i])
			}
		}
	}
}

func TestDisarmTProxyFamily_WithQuotedComments(t *testing.T) {
	saveOutput := `*mangle
:PREROUTING ACCEPT [0:0]
-A PREROUTING -m comment --comment "XKeen TProxy PREROUTING" -j xkeen
-A xkeen -p tcp -m comment --comment "XKeen TProxy Interception" -j TPROXY --on-port 7892 --on-ip 127.0.0.1 --tproxy-mark 0x1/0x1
COMMIT
`
	saveBin, delBin, logPath := installFakeIptables(t, saveOutput)

	removed, ok := disarmTProxyFamily(context.Background(), saveBin, delBin)
	if !ok {
		t.Fatal("expected ok=true")
	}
	if removed != 2 {
		t.Fatalf("expected 2 rules removed, got %d", removed)
	}

	logData, err := os.ReadFile(logPath)
	if err != nil {
		t.Fatalf("expected deletions to have been logged: %v", err)
	}
	log := string(logData)
	if !strings.Contains(log, "XKeen TProxy Interception") {
		t.Errorf("expected comment to be preserved in deletion arguments, log:\n%s", log)
	}
}

func TestEnsureDefaultMihomoConfig_CreatesWhenMissing(t *testing.T) {
	tmpDir := t.TempDir()
	if err := EnsureDefaultMihomoConfig(tmpDir); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	path := filepath.Join(tmpDir, "config.yaml")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("expected config.yaml to be created: %v", err)
	}
	if len(data) == 0 {
		t.Fatal("expected non-empty default config.yaml")
	}
}

func TestEnsureDefaultMihomoConfig_NoOpWhenConfigExists(t *testing.T) {
	tmpDir := t.TempDir()
	path := filepath.Join(tmpDir, "config.yaml")
	original := []byte("mixed-port: 1234\n")
	if err := os.WriteFile(path, original, 0644); err != nil {
		t.Fatal(err)
	}

	if err := EnsureDefaultMihomoConfig(tmpDir); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(data) != string(original) {
		t.Fatal("expected existing config.yaml to be left untouched")
	}
}

func TestEnsureDefaultMihomoConfig_NoOpWhenYmlExists(t *testing.T) {
	tmpDir := t.TempDir()
	ymlPath := filepath.Join(tmpDir, "config.yml")
	if err := os.WriteFile(ymlPath, []byte("mixed-port: 1234\n"), 0644); err != nil {
		t.Fatal(err)
	}

	if err := EnsureDefaultMihomoConfig(tmpDir); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	yamlPath := filepath.Join(tmpDir, "config.yaml")
	if _, err := os.Stat(yamlPath); err == nil {
		t.Fatal("expected config.yaml NOT to be created when config.yml already exists")
	}
}

func TestEnsureDefaultMihomoConfig_NoOpWhenDirMissing(t *testing.T) {
	tmpDir := t.TempDir()
	missing := filepath.Join(tmpDir, "does-not-exist")

	if err := EnsureDefaultMihomoConfig(missing); err != nil {
		t.Fatalf("expected nil error for a missing directory, got %v", err)
	}
	if _, err := os.Stat(missing); err == nil {
		t.Fatal("expected EnsureDefaultMihomoConfig not to create the directory itself")
	}
}

func TestValidateXrayRoutingTags_NoIssues(t *testing.T) {
	tmpDir := t.TempDir()
	outbounds := `{"outbounds":[{"tag":"PROXY_TAG","protocol":"freedom"},{"tag":"direct","protocol":"freedom"},{"tag":"block","protocol":"blackhole"}]}`
	routing := `{"routing":{"rules":[{"type":"field","ip":["geoip:private"],"outboundTag":"direct"},{"type":"field","domain":["geosite:category-ads-all"],"outboundTag":"block"}]}}`
	if err := os.WriteFile(filepath.Join(tmpDir, "04_outbounds.json"), []byte(outbounds), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(tmpDir, "05_routing.json"), []byte(routing), 0644); err != nil {
		t.Fatal(err)
	}

	if issues := ValidateXrayRoutingTags(tmpDir); len(issues) != 0 {
		t.Fatalf("expected no issues, got %v", issues)
	}
}

func TestValidateXrayRoutingTags_DetectsDanglingTag(t *testing.T) {
	tmpDir := t.TempDir()
	outbounds := `{"outbounds":[{"tag":"direct","protocol":"freedom"}]}`
	routing := `{"routing":{"rules":[{"type":"field","domain":["geosite:geolocation-!cn"],"outboundTag":"PROXY_TAG_TYPO"}]}}`
	if err := os.WriteFile(filepath.Join(tmpDir, "04_outbounds.json"), []byte(outbounds), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(tmpDir, "05_routing.json"), []byte(routing), 0644); err != nil {
		t.Fatal(err)
	}

	issues := ValidateXrayRoutingTags(tmpDir)
	if len(issues) != 1 {
		t.Fatalf("expected exactly 1 issue, got %v", issues)
	}
}

func TestValidateXrayRoutingTags_NoOutboundFragments(t *testing.T) {
	tmpDir := t.TempDir()
	if issues := ValidateXrayRoutingTags(tmpDir); len(issues) != 0 {
		t.Fatalf("expected no issues when there are no outbound fragments, got %v", issues)
	}
}
