const { execFileSync } = require('child_process');

function getCommitMessages(base, head) {
  try {
    const range = base && head ? `${base}..${head}` : 'origin/main..HEAD';
    console.log(`Получение коммитов для диапазона: ${range}`);

    // Получаем email автора, заголовок и тело коммитов разделенные специальным маркером
    // execFileSync не использует shell, поэтому аргументы передаются напрямую (без инъекций)
    const output = execFileSync('git', ['log', '--format=%ae%n%s%n%b%n---COMMIT_END---', range], { encoding: 'utf8' });
    return output
      .split('---COMMIT_END---')
      .map(c => c.trim())
      .filter(c => c.length > 0);
  } catch (err) {
    console.error('❌ Ошибка при получении истории коммитов git:', err.message);
    process.exit(1);
  }
}

const base = process.argv[2];
const head = process.argv[3];

const gitRefRegex = /^[a-zA-Z0-9/._-]+$/;
if (base && !gitRefRegex.test(base)) {
  console.error('❌ Ошибка: Неверный формат аргумента base');
  process.exit(1);
}
if (head && !gitRefRegex.test(head)) {
  console.error('❌ Ошибка: Неверный формат аргумента head');
  process.exit(1);
}

const commits = getCommitMessages(base, head);

if (commits.length === 0) {
  console.log('✅ Нет коммитов для проверки.');
  process.exit(0);
}

// Регулярное выражение для Conventional Commits (с опциональным скопом и флагом breaking change !)
const conventionalRegex = /^(feat|fix|docs|style|refactor|perf|test|chore|ci)(?:\([^)]+\))?!?: (.*)$/s;
const cyrillicRegex = /[а-яА-ЯёЁ]/;

let hasErrors = false;

commits.forEach((commitContent, idx) => {
  const lines = commitContent.split('\n');
  const authorEmail = lines[0];
  const subject = lines[1];
  console.log(`\nПроверка коммита #${idx + 1}: "${subject}" (Автор: ${authorEmail})`);

  // 1. Проверяем формат Conventional Commits
  // Игнорируем мерж-коммиты
  if (subject.startsWith('Merge pull request') || subject.startsWith('Merge branch') || subject.startsWith('Merge:')) {
    console.log('  - Игнорируется (коммит слияния)');
    return;
  }

  // Если коммит сделан dependabot, пропускаем проверку языка и формата
  if (/dependabot/i.test(authorEmail)) {
    console.log('  - Игнорируется (коммит Dependabot)');
    return;
  }

  const match = subject.match(conventionalRegex);
  if (!match) {
    console.error('❌ Ошибка: Заголовок не соответствует формату Conventional Commits v1.0.0.');
    console.error('  Пример: feat(backend): добавить новую функцию');
    hasErrors = true;
    return;
  }

  const description = match[2];

  // 2. Проверяем русский язык в описании заголовка
  if (!cyrillicRegex.test(description)) {
    console.error(`❌ Ошибка: Описание коммита ("${description}") должно быть написано на русском языке.`);
    hasErrors = true;
  }

  // 3. Проверяем тело коммита (если оно есть)
  if (lines.length > 2) {
    const body = lines.slice(2).join('\n').trim();
    if (body.length > 0) {
      // Исключаем из проверки ссылки на PR и issue, которые генерируются автоматически
      const isAutoGenerated = body.includes('Co-authored-by:') || body.includes('Merge pull request');
      if (!isAutoGenerated && !cyrillicRegex.test(body)) {
        console.error('❌ Ошибка: Тело коммита должно содержать текст на русском языке.');
        hasErrors = true;
      }
    }
  }
});

if (hasErrors) {
  console.error('\n❌ Проверка коммитов не пройдена! Пожалуйста, исправьте сообщения коммитов.');
  process.exit(1);
} else {
  console.log('\n✅ Все коммиты соответствуют правилам репозитория!');
  process.exit(0);
}
